changed makefile to not copy to vim4js tags/

diff --git a/genAllExtTags b/genAllExtTags
--- a/genAllExtTags
+++ b/genAllExtTags
@@ -5,15 +5,20 @@ if [ -z $1 ];then
 	exit 1
 fi
 SRC=$1
+if [ -z $2 ];then
+	echo "output directory is required as second argument"
+	exit 1
+fi
+OUTPUT_DIR=$2
 #the scripts are in EXT_HOME
 EXT=$EXT_HOME
-INFO_FILE="$EXT/info"
-TMP_FILE="${EXT}/tmp.tags"
+INFO_FILE="$OUTPUT_DIR/info"
+TMP_FILE="$OUTPUT_DIR/tmp.tags"
 rm $INFO_FILE
 touch $INFO_FILE
 
 $EXT/genExtTags $SRC $INFO_FILE >  $TMP_FILE
 
-$EXT/replacePointers.pl $TMP_FILE > $EXT/tags
+$EXT/replacePointers.pl $TMP_FILE > $OUTPUT_DIR/tags
 
 rm $TMP_FILE
