refactored to make reusable on other source tree

diff --git a/genAllExtTags b/genAllExtTags
--- a/genAllExtTags
+++ b/genAllExtTags
@@ -1,6 +1,11 @@
 #!/bin/bash
 #wrapper to generate sorted tags file in same dir
+if [ -z $1 ];then
+	echo "source directory containing js files is required argument"
+	exit 1
+fi
+SRC=$1
 TMP_FILE="tmp.tags"
-./genExtTags >  $TMP_FILE
+./genExtTags $SRC >  $TMP_FILE
 ./replacePointers.pl $TMP_FILE > tags
 rm $TMP_FILE
diff --git a/genExtTags b/genExtTags
--- a/genExtTags
+++ b/genExtTags
@@ -1,7 +1,12 @@
 #!/bin/bash
 #generate tags for Ext.js source code
 # (or Ext.js project which follows same code conventions)
-EXT_SRC="${EXT_HOME}/src"
+
+if [ -z $1 ];then
+	echo "source directory containing js files is required argument"
+	exit 1
+fi
+SRC=$1
 
 echo '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/'
 echo '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/'
@@ -10,6 +15,7 @@ echo '!_TAG_PROGRAM_NAME	Exuberant Ctags	'
 echo '!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	'
 echo '!_TAG_PROGRAM_VERSION	5.8	//'
 
-for file in $(find $EXT_SRC -name "*.js"); do
-	./getExtTags.pl $file
+for file in $(find $SRC -name "*.js"); do
+	${EXT_HOME}/getExtTags.pl $file
 done
+
